INSERT INTO user_preferences (id, user_id,newsletter,share_info,notify) VALUES ( 1, 1000, true , false ,true)
INSERT INTO user_preferences (id, user_id,newsletter,share_info,notify) VALUES ( 2, 2000, false , false ,false )
INSERT INTO user_preferences (id, user_id,newsletter,share_info,notify) VALUES ( 3, 3000, true , true ,true)
INSERT INTO user_preferences (id, user_id,newsletter,share_info,notify) VALUES ( 4, 4000, false , false ,true)
INSERT INTO user_preferences (id, user_id,newsletter,share_info,notify) VALUES ( 5, 5000, false , true ,true)
INSERT INTO Users (user,value) VALUES('User1',1000)
INSERT INTO Users (user,value) VALUES('User2',2000)
INSERT INTO Users (user,value) VALUES('User3',3000)
INSERT INTO Users (user,value) VALUES('User4',4000)
INSERT INTO Users (user,value) VALUES('User5',5000)
